baseURL = "https://zshahid.netlify.com/"
languageCode = "en-uk"
title = "Zain Shahid PhD Journal"
theme = "terminal"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "Entries"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "orange"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 0
  # show selector to switch language
  showLanguageSelector = false
  # set theme to full screen width
  fullWidthTheme = false 
  # center theme with default width
  centerTheme = true
  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

[languages]
  [languages.en]
    languageName = "English"
    title = "Drizzy"
    subtitle = ""
    keywords = ""
    copyright = ""
    menuMore = "Menu"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Drizzy"
      logoHomeLink = "/about"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "PhD Entries"
        name = "PhD Entries"
        url = "/PhD_Entries"
      [[languages.en.menu.main]]
        identifier = "Life Entries"
        name = "Life Entries"
        url = "/Life_Entries"

  [languages.es]
    languageName = "Spanish"
    title = "Terminal"
    subtitle = "A simple, retro theme for Hugo"
    keywords = ""
    copyright = ""
    menuMore = "Menú"
    readMore = "Lee Más"
    readOtherPosts = "Lee otras notas"

    [languages.es.params.logo]
      logoText = "Drizzy"
      logoHomeLink = "/Información"

    [languages.es.menu]
      [[languages.es.menu.main]]
        identifier = "Información"
        name = "Información"
        url = "/Información"
      [[languages.es.menu.main]]
        identifier = "Doctorado"
        name = "Doctorado"
        url = "/Doctorado"
      [[languages.es.menu.main]]
        identifier = "La Vida"
        name = "La Vida"
        url = "/La_Vida"