baseURL = "https://zshahid.netlify.com"
theme = "terminal"
paginate = 100
DefaultContentLanguage = "en"
copyright = '''
  <!DOCTYPE html>
    <html>
      <head>
        <style>
          * {
          box-sizing: border-box;
          }

  .column {
    float: left;
    width: 20%;
    padding: 60px;
  }

  /* Clearfix (clear floats) */
  .row::after {
    content: "";
    clear: both;
    display: table;
  }
  </style>
      </head>

<div class="row">
  <div class="column">
    <a href="https://www.twitter.com/" target="_blank">
      <img src="/icons/twitter.png"
    </a>
  </div>
  <div class="column">
    <a href="https://www.linkedin.com/in/zshahidresearch/" target="_blank">
      <img src="/icons/linkedin.png"
    </a>
  </div>
  <div class="column">
    <a href="https://gitlab.com/shahidzain67/" target="_blank">
      <img src="/icons/gitlab.png"
    </a>
  </div>
  <div class="column">
    <a href="https://orcid.org/0000-0002-2998-2058" target="_blank">
      <img src="/icons/orcid.png "
    </a>
  </div>
  <div class="column">
    <a href="mailto:shahidzain67@gmail.com?Subject=Hello" target="_top">
      <img src="/icons/gmail.png"
    </a>
  </div>
</div>
</html>
'''

defaultContentLanguageInSubdir = true
preserveTaxonomyNames = true

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "Entries"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "orange"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 8
  # show selector to switch language
  showLanguageSelector = false
  # set theme to full screen width
  fullWidthTheme = false 
  # center theme with default width
  centerTheme = true
  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  menuMore = "Show more"
  readMore = "Read more"
  readOtherPosts = "Read other posts"

[taxonomies]
  tag = "tags"
  category = "categories"

[languages]
  [languages.en]
    languageCode = "en-uk"
    languageName = "English"
    title = "Drizzy"
    weight = 2
    readMore = "Read more"
    readOtherPosts = "Read other posts"
  
  [languages.en.params.logo]
    logoText = "Drizzy"
    logoHomeLink = "/"

  [languages.en.menu]
    [[languages.en.menu.main]]
      identifier = "Project"
      name = "Project"
      url = "/tags/project/"
      weight = 6
    [[languages.en.menu.main]]
      identifier = "P&O Fundamentals"
      name = "P&O Fundamentals"
      url = "/tags/fundamentals-of-prosthetics-and-orthotics/"
      weight = 5
    [[languages.en.menu.main]]
      identifier = "GitLab"
      name = "GitLab"
      url = "https://gitlab.com/shahidzain67/phd-journal-tracking"
      weight = 4
    [[languages.en.menu.main]]
      identifier = "Blackboard"
      name = "Blackboard"
      url = "https://blackboard.salford.ac.uk/webapps/portal/execute/tabs/tabAction?tab_tab_group_id=_2_1"
      weight = 3
    [[languages.en.menu.main]]
      identifier = "Anatomy"
      name = "Anatomy"
      url = "tags/anatomy/"
      weight = 2
    [[languages.en.menu.main]]
      identifier = "About"
      name = "About"
      url = "/entries/about/"
      weight = 1