
baseURL = "https://zshahid.netlify.com"
theme = "terminal"
paginate = 100
DefaultContentLanguage = "en"
copyright = "Zain Shahid: PhD Doctoral Candidate in Prosthetics and Orthotics: https://gitlab.com/shahidzain67/phd-journal-tracking"
defaultContentLanguageInSubdir = true
preserveTaxonomyNames = true

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "Entries"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "orange"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 0
  # show selector to switch language
  showLanguageSelector = false
  # set theme to full screen width
  fullWidthTheme = false 
  # center theme with default width
  centerTheme = true
  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

[languages]
  [languages.en]
    languageCode = "en-uk"
    languageName = "English"
    title = "Drizzy"
    weight = 2
    readMore = "Read more"
    readOtherPosts = "Read other posts"
  
  [languages.en.params.logo]
    logoText = "Drizzy"
    logoHomeLink = "/"

[taxonomies]
   tag = "tags"
   category = "categories"

[[menu.main]]
  name = "GitLab"
  weight = 0
  identifier = "GitLab"
  url = "https://gitlab.com/shahidzain67/phd-journal-tracking"

[[menu.main]]
  name = "Blackboard"
  weight = 0
  identifier = "Blackboard"
  url = "https://blackboard.salford.ac.uk/webapps/portal/execute/tabs/tabAction?tab_tab_group_id=_2_1"