baseURL = "https://zshahid.netlify.com"
theme = "terminal"
paginate = 100
DefaultContentLanguage = "en"
copyright = "Zain Shahid: PhD Doctoral Candidate in Prosthetics and Orthotics: https://gitlab.com/shahidzain67/phd-journal-tracking"
defaultContentLanguageInSubdir = true
preserveTaxonomyNames = true

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "Entries"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "orange"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 8
  # show selector to switch language
  showLanguageSelector = false
  # set theme to full screen width
  fullWidthTheme = false 
  # center theme with default width
  centerTheme = true
  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

# [taxonomies]
#   tag = "tags"
#   category = "categories"

[languages]
  [languages.en]
    languageCode = "en-uk"
    languageName = "English"
    title = "Drizzy"
    weight = 2
    readMore = "Read more"
    readOtherPosts = "Read other posts"
  
  [languages.en.params.logo]
    logoText = "Drizzy"
    logoHomeLink = "/"

  [languages.en.menu]
    [[languages.en.menu.main]]
      identifier = "Project"
      name = "Project"
      url = "/tags/project/"
      weight = 6
    [[languages.en.menu.main]]
      identifier = "P&O Fundamentals"
      name = "P&O Fundamentals"
      url = "/tags/fundamentals-of-prosthetics-and-orthotics/"
      weight = 5
    [[languages.en.menu.main]]
      identifier = "Imperial Blackboard"
      name = "Imperial Blackboard"
      url = "https://bb.imperial.ac.uk/webapps/blackboard/content/listContent.jsp?course_id=_19745_1&content_id=_1625767_1&mode=reset"
      weight = 4
    [[languages.en.menu.main]]
      identifier = "GitLab"
      name = "GitLab"
      url = "https://gitlab.com/shahidzain67/phd-journal-tracking"
      weight = 3
    [[languages.en.menu.main]]
      identifier = "Salford Blackboard"
      name = "Salford Blackboard"
      url = "https://blackboard.salford.ac.uk/webapps/portal/execute/tabs/tabAction?tab_tab_group_id=_2_1"
      weight = 2
    [[languages.en.menu.main]]
      identifier = "Anatomy"
      name = "Anatomy"
      url = "https://zshahid.netlify.com/tags/anatomy/"
      weight = 1