baseURL = "https://zshahid.netlify.com"
theme = "terminal"
paginate = 100
DefaultContentLanguage = "en"
copyright = "Zain Shahid: PhD Doctoral Candidate in Prosthetics and Orthotics: https://gitlab.com/shahidzain67/phd-journal-tracking"
defaultContentLanguageInSubdir = true
preserveTaxonomyNames = true

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "Entries"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "orange"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 8
  # show selector to switch language
  showLanguageSelector = false
  # set theme to full screen width
  fullWidthTheme = false 
  # center theme with default width
  centerTheme = true
  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

[languages]
  [languages.en]
    languageCode = "en-uk"
    languageName = "English"
    title = "Drizzy"
    weight = 2
    readMore = "Read more"
    readOtherPosts = "Read other posts"
  
  [languages.en.params.logo]
    logoText = "Drizzy"
    logoHomeLink = "/"

# [taxonomies]
#   tag = "tags"
#   category = "categories"

[menu]

  [[menu.main]]
    name = "Project"
    weight = 6
    identifier = "Project"
    url = "https://zain-phd.netlify.com/tags/project/"

  [[menu.main]]
    name = " P&O Fundamentals"
    weight = 5
    identifier = "P&O Fundamentals"
    url = "https://zain-phd.netlify.com/tags/fundamentals-of-prosthetics-and-orthotics/"

  [[menu.main]]
    name = "Imperial Blackboard"
    weight = 4
    identifier = "Imperial Blackboard"
    url = "https://bb.imperial.ac.uk/webapps/blackboard/content/listContent.jsp?course_id=_19745_1&content_id=_1625767_1&mode=reset"

  [[menu.main]]
    name = "GitLab"
    weight = 3
    identifier = "GitLab"
    url = "https://gitlab.com/shahidzain67/phd-journal-tracking"

  [[menu.main]]
    name = "Blackboard"
    weight = 2
    identifier = "Blackboard"
    url = "https://blackboard.salford.ac.uk/webapps/portal/execute/tabs/tabAction?tab_tab_group_id=_2_1"

  [[menu.main]]
    name = "Anatomy"
    weight = 1
    identifier = "Anatomy"
    url = "https://zain-phd.netlify.com/tags/anatomy/"